steps:
  # 1. Pull the previous build to use as a cache source
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull europe-west4-docker.pkg.dev/project-0f2740f8-acd1-43a1-a04/enterprise-graph-rag-repo/enterprise-rag:latest || true

  # 2. Build the container image using the cache
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--cache-from', 'europe-west4-docker.pkg.dev/project-0f2740f8-acd1-43a1-a04/enterprise-graph-rag-repo/enterprise-rag:latest',
      '-t', 'europe-west4-docker.pkg.dev/project-0f2740f8-acd1-43a1-a04/enterprise-graph-rag-repo/enterprise-rag:latest',
      '.'
    ]

  # 3. Push the compiled image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west4-docker.pkg.dev/project-0f2740f8-acd1-43a1-a04/enterprise-graph-rag-repo/enterprise-rag:latest']

  # 4. Deploy the Streamlit application to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'enterprise-rag'
      - '--image'
      - 'europe-west4-docker.pkg.dev/project-0f2740f8-acd1-43a1-a04/enterprise-graph-rag-repo/enterprise-rag:latest'
      - '--region'
      - 'europe-west4'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'CONFIG_BUCKET_NAME=enterprise-rag-storage-avathon,GOOGLE_CLOUD_PROJECT=project-0f2740f8-acd1-43a1-a04'

images:
  - 'europe-west4-docker.pkg.dev/project-0f2740f8-acd1-43a1-a04/enterprise-graph-rag-repo/enterprise-rag:latest'
